#!/usr/bin/env swift

//
//  load_versions.swift
//  Script to load version information from build files into app settings
//

import Foundation

let projectRoot = FileManager.default.currentDirectoryPath
let fileManager = FileManager.default

// Read app version
func readAppVersion() -> String? {
    let versionFile = "\(projectRoot)/.app_version"
    return try? String(contentsOfFile: versionFile, encoding: .utf8).trimmingCharacters(in: .whitespacesAndNewlines)
}

// Read module version
func readModuleVersion(_ moduleName: String) -> String? {
    let versionFile = "\(projectRoot)/.\(moduleName)_version"
    return try? String(contentsOfFile: versionFile, encoding: .utf8).trimmingCharacters(in: .whitespacesAndNewlines)
}

// All module names
let modules = ["AppKitBridge", "AudioCore", "MetadataEngine", "DataLayer", "UI", "PluginSystem", "Shared"]

// Generate Swift code to update versions
var swiftCode = """
// Auto-generated version update code
// This file is generated by load_versions.swift script

import Foundation

func updateVersions() {
    let versionManager = VersionManager.shared

    // Update app version
"""

if let appVersion = readAppVersion() {
    swiftCode += """
    if let version = Version(from: "\(appVersion)") {
        versionManager.setAppVersion(version)
    }

    // Update module versions
"""
} else {
    swiftCode += """
    // App version not found, using current
    let appVersion = versionManager.generateCurrentVersion()
    versionManager.setAppVersion(appVersion)

    // Update module versions
"""
}

for module in modules {
    if let moduleVersion = readModuleVersion(module) {
        swiftCode += """
    if let version = Version(from: "\(moduleVersion)") {
        versionManager.setVersion(version, for: "\(module)")
    }
"""
    }
}

swiftCode += """
}

// Call update on app launch
updateVersions()
"""

// Write to output file
let outputFile = "\(projectRoot)/Shared/Utilities/AutoVersionUpdate.swift"
try? swiftCode.write(toFile: outputFile, atomically: true, encoding: .utf8)
